### ISSUE TITLE
'IllegalStateException: Couldn't find declaration file' on delegate with inline getValue operator

### ISSUE THREAD

**Issue by osipxd** [RedMadRobot/mapmemory#11]
### Steps to reproduce

1. Have kapt enabled and have any dependency with kapt configuration
2. Use the following code:
```kotlin
@Singleton
class SessionMemory @Inject constructor() : MapMemory()

class SomeStorage(memory: SessionMemory) {
    val someValue: String by memory // <-- Exception thrown here 
}
```

### Actual result
```
java.lang.IllegalStateException: Couldn't find declaration file for com/example/DelegateSubclass
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$Companion.doCreateMethodNodeFromCompiled(InlineCodegen.kt:649)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$Companion.getCompiledMethodNodeInner(InlineCodegen.kt:590)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$Companion.createSpecialInlineMethodNodeFromBinaries$backend(InlineCodegen.kt:576)
	at org.jetbrains.kotlin.codegen.DelegatedPropertiesCodegenHelper.isDelegatedPropertyMetadataRequiredForFunctionFromBinaries(DelegatedPropertiesCodegenHelper.kt:73)
	at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:243)
	at org.jetbrains.kotlin.psi.KtFile.accept(KtFile.kt:230)
	at org.jetbrains.kotlin.codegen.binding.CodegenBinding.initTrace(CodegenBinding.java:101)
	at org.jetbrains.kotlin.codegen.state.GenerationState.beforeCompile(GenerationState.kt:350)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:31)
	...
```

**Comment by osipxd** [comment]
This bug is caused by the Kotlin Compiler bug: [KT-46317](https://youtrack.jetbrains.com/issue/KT-46317)
